// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "msisdn/swagger/models"
)

// ParseMsisdnOKCode is the HTTP code returned for type ParseMsisdnOK
const ParseMsisdnOKCode int = 200

/*ParseMsisdnOK returns parsed msisdn

swagger:response parseMsisdnOK
*/
type ParseMsisdnOK struct {

	/*
	  In: Body
	*/
	Payload *models.ParsedMsisdn `json:"body,omitempty"`
}

// NewParseMsisdnOK creates ParseMsisdnOK with default headers values
func NewParseMsisdnOK() *ParseMsisdnOK {

	return &ParseMsisdnOK{}
}

// WithPayload adds the payload to the parse msisdn o k response
func (o *ParseMsisdnOK) WithPayload(payload *models.ParsedMsisdn) *ParseMsisdnOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the parse msisdn o k response
func (o *ParseMsisdnOK) SetPayload(payload *models.ParsedMsisdn) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ParseMsisdnOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ParseMsisdnNotFoundCode is the HTTP code returned for type ParseMsisdnNotFound
const ParseMsisdnNotFoundCode int = 404

/*ParseMsisdnNotFound error

swagger:response parseMsisdnNotFound
*/
type ParseMsisdnNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.NotFound `json:"body,omitempty"`
}

// NewParseMsisdnNotFound creates ParseMsisdnNotFound with default headers values
func NewParseMsisdnNotFound() *ParseMsisdnNotFound {

	return &ParseMsisdnNotFound{}
}

// WithPayload adds the payload to the parse msisdn not found response
func (o *ParseMsisdnNotFound) WithPayload(payload *models.NotFound) *ParseMsisdnNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the parse msisdn not found response
func (o *ParseMsisdnNotFound) SetPayload(payload *models.NotFound) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ParseMsisdnNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
