consumes:
  - application/json
info:
  description: msisdn parser
  title: msisdn
  version: 0.1.0
produces:
  - application/json
schemes:
  - http
swagger: "2.0"

basePath: /msisdn
paths:
  /parse:
    get:
      operationId: "parseMsisdn"
      parameters:
        - in: formData
          name: msisdn
          type: string
          required: true
      responses:
        200:
          description: 'returns parsed msisdn'
          schema:
            $ref: "#/definitions/ParsedMsisdn"
        404:
          description: 'error'
          schema:
            $ref: "#/definitions/NotFound"

definitions:
  NotFound:
    description: 'Error object'
    type: object
    properties:
      code:
        type: integer
      message:
        type: string
  ParsedMsisdn:
    description: 'Object with parsed msisdn values'
    type: object
    properties:
      MNO:
        type: string
      CDC:
        type: string
      SN:
        type: string
      CI:
        type: string