// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi msisdn
msisdn parser


    Schemes:
      http
    Host: localhost
    BasePath: /msisdn
    Version: 0.1.0

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
