// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "msisdn parser",
    "title": "msisdn",
    "version": "0.1.0"
  },
  "basePath": "/msisdn",
  "paths": {
    "/parse": {
      "get": {
        "operationId": "parseMsisdn",
        "parameters": [
          {
            "type": "string",
            "name": "msisdn",
            "in": "formData",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "returns parsed msisdn",
            "schema": {
              "$ref": "#/definitions/ParsedMsisdn"
            }
          },
          "404": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/NotFound"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "NotFound": {
      "description": "Error object",
      "type": "object",
      "properties": {
        "code": {
          "type": "integer"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "ParsedMsisdn": {
      "description": "Object with parsed msisdn values",
      "type": "object",
      "properties": {
        "MNO_id": {
          "type": "string"
        },
        "country_code": {
          "type": "string"
        },
        "country_id": {
          "type": "string"
        },
        "subscriber_number": {
          "type": "string"
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "msisdn parser",
    "title": "msisdn",
    "version": "0.1.0"
  },
  "basePath": "/msisdn",
  "paths": {
    "/parse": {
      "get": {
        "operationId": "parseMsisdn",
        "parameters": [
          {
            "type": "string",
            "name": "msisdn",
            "in": "formData",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "returns parsed msisdn",
            "schema": {
              "$ref": "#/definitions/ParsedMsisdn"
            }
          },
          "404": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/NotFound"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "NotFound": {
      "description": "Error object",
      "type": "object",
      "properties": {
        "code": {
          "type": "integer"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "ParsedMsisdn": {
      "description": "Object with parsed msisdn values",
      "type": "object",
      "properties": {
        "MNO_id": {
          "type": "string"
        },
        "country_code": {
          "type": "string"
        },
        "country_id": {
          "type": "string"
        },
        "subscriber_number": {
          "type": "string"
        }
      }
    }
  }
}`))
}
