// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// ParsedMsisdn Object with parsed msisdn values
// swagger:model ParsedMsisdn
type ParsedMsisdn struct {

	// m n o id
	MNOID string `json:"MNO_id,omitempty"`

	// country code
	CountryCode string `json:"country_code,omitempty"`

	// country id
	CountryID string `json:"country_id,omitempty"`

	// subscriber number
	SubscriberNumber string `json:"subscriber_number,omitempty"`
}

// Validate validates this parsed msisdn
func (m *ParsedMsisdn) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ParsedMsisdn) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ParsedMsisdn) UnmarshalBinary(b []byte) error {
	var res ParsedMsisdn
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
